{
  pkgs,
  helium,
  kopuz,
  nixpkgs-unstable,
  ...
}:

let
  unstable = import nixpkgs-unstable {
    system = pkgs.stdenv.hostPlatform.system;
    config.allowUnfree = true; # only needed if the package is unfree
  };
in

{
  environment.systemPackages = with pkgs; [
    wget
    curl
    kdePackages.kdeconnect-kde
    kdePackages.partitionmanager
    kdePackages.krdc
    kdePackages.kleopatra
    kdePackages.kcalc
    kdePackages.spectacle
    kdePackages.plasma-workspace
    steam-devices-udev-rules
    gamemode
    gamescope
    lutris
    libdecor
    zed-editor
    bitwarden-desktop
    cifs-utils
    rsync
    vscodium
    claude-code
    unstable.opencode
    git
    unstable.netbird
    unstable.netbird-ui
    dig
    wine-staging
    fastfetch
    hyfetch
    gh
    python3
    unzip
    zip
    unrar
    gparted
    binutils
    usbutils
    vim
    file
    android-tools
    refind
    winetricks
    nixd
    nil
    distrobox
    helium.packages.${system}.default
    kopuz.packages.${system}.default
    cloc
    poedit
    cider-2
    kdePackages.kleopatra
    gnupg
    pinentry-all
    krita
    nix-output-monitor
    socat
    prismlauncher
    xwayland-satellite
    gparted
    waywallen
    wl-clipboard
    jellyfin-desktop
    jellyfin-rpc
    discord
    bun
    playwright-driver.browsers
    figma-linux
    nodejs
    pnpm
    filezilla
    tailscale
    feishin
    swaybg
    mtr
    whois
    ansible
    amdctl
    stress-ng
    lm_sensors
    ryzenadj
    libreoffice-fresh
  ];

  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    nerd-fonts.fira-code
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
    departure-mono
    gohufont
  ];
}
