{
  pkgs,
  helium,
  kopuz,
  ...
}:

{
  environment.systemPackages = with pkgs; [
    wget
    curl
    kdePackages.kdeconnect-kde
    kdePackages.partitionmanager
    kdePackages.krdc
    kdePackages.kleopatra
    kdePackages.kcalc
    kdePackages.spectacle
    kdePackages.plasma-workspace
    steam-devices-udev-rules
    gamemode
    gamescope
    lutris
    libdecor
    zed-editor
    bitwarden-desktop
    cifs-utils
    rsync
    vscodium
    claude-code
    opencode
    git
    netbird
    netbird-ui
    dig
    wine-staging
    fastfetch
    hyfetch
    gh
    python3
    unzip
    zip
    gparted
    binutils
    usbutils
    vim
    file
    android-tools
    refind
    winetricks
    nixd
    nil
    distrobox
    helium.packages.${system}.default
    kopuz.packages.${system}.default
    cloc
    poedit
    cider-2
    kdePackages.kleopatra
    gnupg
    pinentry-all
    krita
    nix-output-monitor
    socat
    prismlauncher
    xwayland-satellite
    gparted
    waywallen
    wl-clipboard
    jellyfin-desktop
    jellyfin-rpc
    discord
    bun
    playwright-driver.browsers
    figma-linux
    nodejs
    pnpm
    filezilla
    tailscale
  ];

  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
    nerd-fonts.fira-code
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-color-emoji
  ];
}
