name: Check NixOS config

on: [push]

jobs:
  check:
    runs-on: nix-flakes
    steps:

      - name: Install Node.js
        run: |
          nix profile install nixpkgs#nodejs
          echo "$HOME/.nix-profile/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4

      - name: Evaluate flake (no build)
        run: nix flake check --no-build --keep-going

      - name: Full nixosConfiguration eval
        run: |
          nix eval .#nixosConfigurations.xiaolong-nix.config.system.build.toplevel

      - name: Post-check cleanup
        if: always()
        run: |
          nix-collect-garbage -d
